# Generated by Django 5.0.1 on 2024-02-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_pasword_profile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
