# Generated by Django 5.0.1 on 2024-02-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
