# Generated by Django 5.0.1 on 2024-03-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
