# Generated by Django 5.0.1 on 2024-03-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_display_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Отображаемое имя'),
        ),
    ]
